In [2]:
import datetime 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from githubanalysis.analysis.analyse_data import DataAnalyser

dataanalyser = DataAnalyser(in_notebook=True, logger=None, dataset_name="joinfixes")
current_date_info = datetime.datetime.now().strftime(
            "%Y-%m-%d"
        )
print(current_date_info)

2025-05-11

In [3]:
commits_data_file = "../../data/commits-data-per-dev_x2320-repos_2025-05-10.csv"
issues_data_file = "../../data/issues-data-per-dev_x2829-repos_x237715-repo-individuals_2025-04-15.csv"

In [24]:
proc_commits_nfce = pd.read_csv("../../data/processed-commits_nf-core-epitopeprediction_2025-04-11.csv")

In [25]:
proc_commits_nfce

,Unnamed: 0,repo_name,branch_sha,commit_sha,author_fullname,author_commit_date,comitter_commit_date,commit_message,author_username,comitter_username
0,0,nf/core/epitopeprediction,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,nf-core-bot,2021-12-14T16:42:45Z,2021-12-14T16:42:45Z,Template update for nf-core/tools version 2.2,nf-core-bot,nf-core-bot
1,1,nf/core/epitopeprediction,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,c9d402ae898ca4f736f004ce8482f69b2af0c42d,nf-core-bot,2021-07-27T15:35:41Z,2021-07-27T15:35:41Z,Template update for nf-core/tools version 2.1,nf-core-bot,nf-core-bot
2,2,nf/core/epitopeprediction,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,d203da61aaf0d8ba948d6cdee381c6baa991ef2d,nf-core-bot,2021-07-13T15:28:28Z,2021-07-13T15:28:28Z,Template update for nf-core/tools version 2.0.1,nf-core-bot,nf-core-bot
3,3,nf/core/epitopeprediction,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,ff317cc749f41b98d895cdacf560651e783d1402,kevinmenden,2021-07-13T08:46:15Z,2021-07-13T08:46:15Z,Template update for nf-core/tools version 2.0,KevinMenden,KevinMenden
4,4,nf/core/epitopeprediction,b6c17ffbbe0a4d099a1006572fb3a39811c55b3f,6150d7da3e285d056910d887354d54948d3ca3d4,nf-core-bot,2021-05-11T11:09:53Z,2021-05-11T11:09:53Z,Template update for nf-core/tools version 1.14,nf-core-bot,nf-core-bot
...,...,...,...,...,...,...,...,...,...,...
958,958,nf/core/epitopeprediction,3d96570b00e32ccda9f916d5120279ef5d1f3012,793a81a82edc9b3f6ebabac34047454009883d5a,mohr,2019-01-23T15:40:07Z,2019-01-23T15:40:07Z,Implement functionality for first version of e...,christopher-mohr,christopher-mohr
959,959,nf/core/epitopeprediction,3d96570b00e32ccda9f916d5120279ef5d1f3012,aecc03448d3e69b6a77b80a15fb6e8ecd6277acc,mohr,2018-11-28T15:30:42Z,2018-11-28T15:30:42Z,Starting to build my pipeline,christopher-mohr,christopher-mohr
960,960,nf/core/epitopeprediction,3d96570b00e32ccda9f916d5120279ef5d1f3012,9bb7208e27a3fb09a759d7f6f59a89f10ec97232,mohr,2018-10-15T08:23:39Z,2018-10-15T08:23:39Z,"initial template build from nf-core/tools, ver...",christopher-mohr,christopher-mohr
961,961,nf/core/epitopeprediction,cfbfeb56b2224ae603539e88088ff4170a01dba6,cfbfeb56b2224ae603539e88088ff4170a01dba6,Jonas Scheid,2024-05-17T12:00:32Z,2024-05-17T12:00:32Z,Merge pull request #238 from nf-core/dev\n\nRe...,jonasscheid,web-flow
962,962,nf/core/epitopeprediction,cfbfeb56b2224ae603539e88088ff4170a01dba6,e173620ac2a10fae8d0a47f597aa723684456deb,Jonas Scheid,2024-02-26T11:49:54Z,2024-02-26T11:49:54Z,Merge pull request #230 from nf-core/dev\n\nRe...,jonasscheid,web-flow

In [4]:
commits_multirepo = pd.read_csv(commits_data_file)
print(f"length of commits df is {len(commits_multirepo)}")

issues_multirepo = pd.read_csv(issues_data_file)
print(f"length of issues df is {len(issues_multirepo)}")    
commits_multirepo = commits_multirepo.drop_duplicates(
    keep="first", ignore_index=True
)
print(f"length of commits df is {len(commits_multirepo)}")
issues_multirepo = issues_multirepo.drop_duplicates(
    keep="first", ignore_index=True
)
print(f"length of issues df is {len(issues_multirepo)}")

length of commits df is 55666
length of issues df is 237715
length of commits df is 55666
length of issues df is 237715

In [5]:

omnirepo = pd.merge(
    left=commits_multirepo,
    right=issues_multirepo,
    how="outer",
    left_on=["author_username", "repo_name"],
    right_on=["issue_username", "repo_name"],
    # validate="one_to_one",
    suffixes=("_commits", "_issues"),
    indicator="commiss_merge",
)
omnirepo

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username,commiss_merge
0,WIPACrepo/iceprod,actions-user,12.0,7.0,0.271108,40.0,5.714286,5.0,1.253566,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,WIPACrepo/iceprod,alemsh,12.0,1.0,0.038730,151.0,151.000000,151.0,NaN,6.0,...,alemsh,1.0,0.234192,18.0,alemsh,1.0,0.390625,both,alemsh,both
2,WIPACrepo/iceprod,carlwitt,12.0,1.0,0.038730,2.0,2.000000,2.0,NaN,1.0,...,carlwitt,2.0,0.468384,18.0,unassigned,0.0,0.000000,left_only,carlwitt,both
3,WIPACrepo/iceprod,dependabot[bot],12.0,10.0,0.387297,24.0,2.400000,2.0,1.264911,12.0,...,dependabot[bot],23.0,5.386417,18.0,unassigned,0.0,0.000000,left_only,dependabot[bot],both
4,WIPACrepo/iceprod,dsschult,12.0,2275.0,88.109992,1117264.0,491.105055,10.0,4118.362826,10371.0,...,dsschult,361.0,84.543326,18.0,dsschult,216.0,84.375000,both,dsschult,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244138,trendscenter/coinstac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,krootesmurdy,5.0,2.590674,right_only,krootesmurdy,right_only
244139,trendscenter/coinstac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,sunithabasodi,10.0,5.181347,right_only,sunithabasodi,right_only
244140,geopython/pygeoapi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,msmitherdc,2.0,0.519481,right_only,msmitherdc,right_only
244141,h2020-westlife-eu/virtualfolder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,chrishmorris,1.0,2.857143,right_only,chrishmorris,right_only
244142,h2020-westlife-eu/virtualfolder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,kouril,1.0,2.857143,right_only,kouril,right_only

In [6]:
omnirepo.query("repo_name.str.count('/') != 1", engine="python")['repo_name'].unique()

array([], dtype=object)

In [7]:
test_repo = omnirepo.query("repo_name == 'nf-core/tools'")
test_repo.query("issue_author_username != None & author_username == None | issue_author_username != None & issue_username == None ")

Empty DataFrame
Columns: [repo_name, author_username, n_of_commit_creators, n_commits, pc_repo_commits, n_changes, mean_n_changes, median_n_changes_changed, std_n_changes_changed, n_files_changed, mean_n_files, median_n_files_changed, std_n_files_changed, hattori_lanza_size_cat_tiny, hattori_lanza_size_cat_small, hattori_lanza_size_cat_medium, hattori_lanza_size_cat_large, hattori_lanza_content_cat_forward_engineering, hattori_lanza_content_cat_reengineering, hattori_lanza_content_cat_corrective_engineering, hattori_lanza_content_cat_management, hattori_lanza_content_cat_empty_message, hattori_lanza_content_cat_no_categorisation, vasilescu_category_doc, vasilescu_category_img, vasilescu_category_l10n, vasilescu_category_ui, vasilescu_category_media, vasilescu_category_code, vasilescu_category_meta, vasilescu_category_config, vasilescu_category_build, vasilescu_category_devdoc, vasilescu_category_db, vasilescu_category_test, vasilescu_category_unknown, issue_author_username, n_issues, pc_repo_issues, n_of_issues_creators, assigned_devs, n_issues_assigned, pc_issues_assigned_of_assigned, _merge, issue_username, commiss_merge]
Index: []

[0 rows x 46 columns]

In [18]:
test_repo.commiss_merge.value_counts()

commiss_merge
right_only    138
both          129
left_only       5
Name: count, dtype: int64

In [19]:
test_repo.query("commiss_merge == 'left_only'")

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username,commiss_merge
41203,nf-core/tools,aelezi01,134.0,4.0,0.031827,1751.0,437.750000,13.5,850.839732,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
41231,nf-core/tools,github-actions[bot],134.0,47.0,0.373966,115497.0,2457.382979,1910.0,1625.121635,862.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
41265,nf-core/tools,nf-core-bot,134.0,320.0,2.546149,942.0,2.943750,1.0,13.473879,352.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
41284,nf-core/tools,rivera10,134.0,1.0,0.007957,1.0,1.000000,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
41299,nf-core/tools,thanhleviet,134.0,1.0,0.007957,4.0,4.000000,4.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [9]:
test_repo.columns

Index(['repo_name', 'author_username', 'n_of_commit_creators', 'n_commits',
       'pc_repo_commits', 'n_changes', 'mean_n_changes',
       'median_n_changes_changed', 'std_n_changes_changed', 'n_files_changed',
       'mean_n_files', 'median_n_files_changed', 'std_n_files_changed',
       'hattori_lanza_size_cat_tiny', 'hattori_lanza_size_cat_small',
       'hattori_lanza_size_cat_medium', 'hattori_lanza_size_cat_large',
       'hattori_lanza_content_cat_forward_engineering',
       'hattori_lanza_content_cat_reengineering',
       'hattori_lanza_content_cat_corrective_engineering',
       'hattori_lanza_content_cat_management',
       'hattori_lanza_content_cat_empty_message',
       'hattori_lanza_content_cat_no_categorisation', 'vasilescu_category_doc',
       'vasilescu_category_img', 'vasilescu_category_l10n',
       'vasilescu_category_ui', 'vasilescu_category_media',
       'vasilescu_category_code', 'vasilescu_category_meta',
       'vasilescu_category_config', 'vasilescu_category_build',
       'vasilescu_category_devdoc', 'vasilescu_category_db',
       'vasilescu_category_test', 'vasilescu_category_unknown',
       'issue_author_username', 'n_issues', 'pc_repo_issues',
       'n_of_issues_creators', 'assigned_devs', 'n_issues_assigned',
       'pc_issues_assigned_of_assigned', '_merge', 'issue_username',
       'commiss_merge'],
      dtype='object')

In [10]:
test_repo.query("author_username == 'ewels' | issue_author_username == 'ewels' | issue_username == 'ewels'")

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username,commiss_merge
41223,nf-core/tools,ewels,134.0,2400.0,19.096117,356583.0,148.57625,12.0,832.510319,10744.0,...,ewels,727.0,20.729969,260.0,ewels,36.0,9.498681,both,ewels,both

In [11]:
test_repo.query("author_username == 'kalexandru' | issue_author_username == 'kalexandru' | issue_username == 'kalexandru'")

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username,commiss_merge
242796,nf-core/tools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,NaN,kalexandru,1.0,0.263852,right_only,kalexandru,right_only

In [21]:
proc_issues = issues_multirepo.query("repo_name == 'nf-core/tools'")
proc_issues = proc_issues.query("issue_username == 'ewels' | issue_username == 'kalexandru' | issue_username == 'nf-core-bot'")
proc_issues

,repo_name,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username
7043,nf-core/tools,ewels,727.0,20.729969,260.0,ewels,36.0,9.498681,both,ewels
235993,nf-core/tools,NaN,0.0,0.000000,NaN,kalexandru,1.0,0.263852,right_only,kalexandru

In [22]:
proc_commits = commits_multirepo.query("repo_name == 'nf-core/tools'")
proc_commits = proc_commits.query("author_username == 'ewels' | author_username == 'kalexandru' | author_username == 'nf-core-bot'")
proc_commits

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,vasilescu_category_ui,vasilescu_category_media,vasilescu_category_code,vasilescu_category_meta,vasilescu_category_config,vasilescu_category_build,vasilescu_category_devdoc,vasilescu_category_db,vasilescu_category_test,vasilescu_category_unknown
41223,nf-core/tools,ewels,134,2400,19.096117,356583.0,148.57625,12.0,832.510319,10744.0,...,0.0,0.0,1232.0,0.0,0.0,11.0,0.0,0.0,2.0,59.0
41265,nf-core/tools,nf-core-bot,134,320,2.546149,942.0,2.94375,1.0,13.473879,352.0,...,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
pd.merge(
    left=proc_commits,
    right=proc_issues,
    how="outer",
    left_on=["author_username", "repo_name"],
    right_on=["issue_username", "repo_name"],
    # validate="one_to_one",
    suffixes=("_commits", "_issues"),
    indicator="commiss_merge",
)

,repo_name,author_username,n_of_commit_creators,n_commits,pc_repo_commits,n_changes,mean_n_changes,median_n_changes_changed,std_n_changes_changed,n_files_changed,...,issue_author_username,n_issues,pc_repo_issues,n_of_issues_creators,assigned_devs,n_issues_assigned,pc_issues_assigned_of_assigned,_merge,issue_username,commiss_merge
0,nf-core/tools,ewels,134.0,2400.0,19.096117,356583.0,148.57625,12.0,832.510319,10744.0,...,ewels,727.0,20.729969,260.0,ewels,36.0,9.498681,both,ewels,both
1,nf-core/tools,nf-core-bot,134.0,320.0,2.546149,942.0,2.94375,1.0,13.473879,352.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,nf-core/tools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.000000,NaN,kalexandru,1.0,0.263852,right_only,kalexandru,right_only

In [ ]:
datafile = "../../data/merged-data-per-dev_x2868-repos_2025-05-10.csv"

In [ ]:
data = pd.read_csv(datafile, header=0, low_memory=False)

In [ ]:
interactions_datafile = "../../data/merged-interactions-data-per-dev_x2942-repos_2025-05-10.csv"

In [ ]:
interactions_data = pd.read_csv(interactions_datafile, header=0, low_memory=False)
interactions_data